### ISSUE TITLE
Fails when running with ansible v2

### ISSUE THREAD

**Issue by trondhindenes** [ks888/ansible-playbook-debugger#2]
Any plans to implement support for Ansible V2?

**Comment by ks888** [comment]
Thank you for asking!

I want to support for v2, but I do not have a clear plan for this. I hope to support for v2 within the year at the latest.

**Comment by trondhindenes** [comment]
That's great news. It's an awesome tool you've built!

**Comment by mcameron** [comment]
+1

**Comment by ks888** [comment]
Sorry the tool still does not support for v2.
I checked ansible v2 internals, and noticed that there are lots of difference between v1 and v2.
So it is not so easy to support for v2, and I can not say when I can make it.

**Comment by jpic** [comment]
A PR would be welcome here, or maybe even inside ansible itself.

**Comment by ghost** [comment]
+1 !

**Comment by ks888** [comment]
I finally start to implement the debugger for ansible v2. Check [support-ansible-v2 branch](https://github.com/ks888/ansible-playbook-debugger/tree/support-ansible-v2), and feel free to open an issue/PR. Read **support-ansible-v2 branch's** README if you try it.

**Comment by ks888** [comment]
Now the debugger v0.3.0 or later supports ansible v2. See master branch's README to use it.

**Comment by ks888** [comment]
Close. Please open a new issue if you find a problem.

**Comment by jpic** [comment]
Way to go !!

Thanks a heap !

:guitar: :musical_score: :muscle: 

Keep up the great work B)
