### ISSUE TITLE
display ansible-playbook original help

### ISSUE THREAD

**Issue by bamarni** [ks888/ansible-playbook-debugger#3]
Thanks for this great tool :+1: 

I'd like to create an alias script for `ansible-playbook` that will use this one instead, the only thing it'd miss is the help instructions from `ansible-playbook`, would it make sense to have those instructions at the bottom?

```
usage: ansible-playbook-debugger [-h] [--version] [--breakpoint TASK_NAME]

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --breakpoint TASK_NAME
                        invoke the debugger before running the task matching
                        this name

Options available for ansible-playbook command are also available : 
[original help from ansible-playbook]
```

**Comment by ks888** [comment]
Thank you for your idea, but I want to keep this tool simple, so I am not going to change the current help.

I don't understand your situation exactly, but how about write a script like this:

```
#!/bin/bash

if echo $@ | grep -e -h; then
  /usr/local/bin/ansible-playbook-debugger $@
  /usr/local/bin/ansible-playbook -h
else
  /usr/local/bin/ansible-playbook-debugger $@
fi
```

**Comment by bamarni** [comment]
Yeah I can do something like this, thanks for the tip :+1:
