### ISSUE TITLE
ERROR! Invalid play strategy specified: debug

### ISSUE THREAD

**Issue by ghost** [ks888/ansible-playbook-debugger#4]
ansible 2.0.1.0

$: ls strategy_plugins/
debug.py

<pre>
ansible.cfg:
strategy_plugins = strategy_plugins/
</pre>

<pre>
playbook:
- hosts: all
  strategy: debug
</pre>

**Comment by ks888** [comment]
`strategy_plugins` configuration is not available on ansible v2.0.1.0. It is merged on `devel` branch already, so I guess it will be available on v2.1.0.
(yes, when you see [ansible docs](http://docs.ansible.com/ansible/intro_configuration.html#strategy-plugins), it looks like you can use it, but it's not)

BTW, if a `strategy_plugins` directory is a child of a playbook directory, you don't need `strategy_plugins` configuration.

**Comment by ghost** [comment]
gah. confused 2.1.0 with 2.0.1.0, and yes - i saw the docs. Doh!
waiting for this plugin with baited breath. I've needed something like it countless times over the last few weeks alone

**Comment by elange** [comment]
This is simply resolved with three commands:
 git submodule --init --update
 git submodule sync
 git submodule update --recursive
