### ISSUE TITLE
Consider submitting to Ansible

### ISSUE THREAD

**Issue by aioue** [ks888/ansible-playbook-debugger#5]
This a really handy, would you consider submitting it to Ansible so everyone can see and use it, please?

https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/strategy

They accept the plugin along with a documentation file of the same written in reStructuredText `.rst`

**Comment by ks888** [comment]
Thank you for using this plugin.

Actually I've just submitted it with some docs. Please leave a comment if you notice any issue.
https://github.com/ansible/ansible/pull/15125

**Comment by aioue** [comment]
Thank you!

**Comment by jpic** [comment]
It has been merged in Ansible, way to go !!!

You rock :guitar:
